### ISSUE TITLE
Expiry 15 minutes

### ISSUE THREAD

**Issue by defuzer** [vikrantkumar158/Email-OTP#1]
Hello, what about expiry password time?

**Comment by vikrantkumar158** [comment]
Okay, will surely work upon it, just in a day or two it would be done. Thanks.

**Comment by defuzer** [comment]
Can you also try add mysql support for this password expiry?

**Comment by defuzer** [comment]
Any progress?

**Comment by vikrantkumar158** [comment]
Would be doing it soon. Due to work from home I am not able to manage my time.
Thanks for your patience.

**Comment by vikrantkumar158** [comment]
Okay I will be using nosql database for password expiry. Do you specifically want me to use mysql???

**Comment by vikrantkumar158** [comment]
Okay I will be using nosql database for password expiry. Do you specifically want me to use mysql???

**Comment by vikrantkumar158** [comment]
Okay I have done the needful, for now it is in the repo, you can check the code. For time being I have currently kept the otp expiry time for 2 mins and I am using mongodb in this. I have updated the website also, and the api would also be updated. Please check it and thanks for your patience.

**Comment by vikrantkumar158** [comment]
If you want this specifically in mySQL then I would surely release another version which would use mySQL only, and if you want to increase the otp expiry and just can't figure it out, then feel free to contact me.

**Comment by defuzer** [comment]
Cool it works like charm.
If you can make mysql version it woul be great!

**Comment by vikrantkumar158** [comment]
Just in 24 hrs, means it won't take that long. It will be done soon.

**Comment by defuzer** [comment]
Cool commit

**Comment by defuzer** [comment]
Any progress with mysql?

**Comment by vikrantkumar158** [comment]
Okay, sorry for being late and thanks for your patience.
Here is the GitHub link https://github.com/vikrantkumar158/Email-Verification
for the repo.
Thanks again for your patience.
